Revert back to django REST framework 3.2.5 because of a bug with later versions
The error occurs with version 3.3.0 and later, with Django 1.9:

AttributeError at /api/v1/panoramas/
'Reference' object has no attribute 'referencepoint_ptr'

It is not clear whether the bug is in django REST framework, Django 1.9,
or our models.